site_name: psychopy-fastrak
site_description: >
    This repository contains a [PsychoPy](https://psychopy.org/) plugin implementing a
    [component](https://psychopy.org/builder/components/index.html#components) exposing tacking data
    from a [six degrees of freedom](https://en.wikipedia.org/wiki/Six_degrees_of_freedom) tracking
    device.
columns:
site_url: https://psychopyfastrak.nontrivialsolutions.com/
theme:
    name: material
    logo: infra/assets/logo.svg
    favicon: infra/assets/favicon.png
    palette:
        - media: "(prefers-color-scheme: light)"
          accent: deep purple
          primary: deep purple
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          accent: deep purple
          primary: deep purple
          scheme: dracula
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.indexes
        - navigation.expand
        - toc.follow
        - navigation.top
        - content.code.copy
repo_name: Nontrivial-Solutions/psychopy-fastrak
repo_url: https://github.com/Nontrivial-Solutions/psychopy-fastrak
extra_css:
    - https://unpkg.com/katex@0/dist/katex.min.css
    - "infra/css/colors.css"
    - "infra/css/admonitions.css"
    - "infra/css/icon.css"
    - "infra/css/authors.css"
    - "infra/css/status.css"

extra_javascript:
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    - "infra/js/extra.js"

watch:
    - docs
    # - psychopy_fastrak

plugins:
    - search:
    - autorefs:
    - bibtex:
          bib_file: "docs/infra/ref.bib"
    - authors:
          authors_file: "infra/.authors.yml"
    - mkdocstrings:
          handlers:
              python:
                  options:
                      docstring_style: "numpy"
                      extensions:
                          - griffe_typingdoc
                      preload_modules:
                          - serial
                      docstring_section_style: spacy
    # - api-autonav:
    #       modules: ["./psychopy_fastrak/"]
    #       nav_section_title: "Implementation Reference"
    #       api_root_uri: "reference"
    - awesome-nav
markdown_extensions:
    - attr_list
    - footnotes
    - pymdownx.arithmatex:
          generic: true
    - toc:
          permalink: 
          separator: "_"
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - overrides/.icons
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          pygments_lang_class: true
          linenums: true
          linenums_style: pymdownx-inline
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.blocks.caption
    - md_in_html
    - gfm_admonition
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/Nontrivial-Solutions/psychopy-fastrak
    status:
        deprecated: Decision is Suggested
        suggested: Decision is Suggested
        in_progress: Decision is in Progress
        accepted: Accepted Decision
        happy: This test is on the happy path
        unhappy: This test is on the unhappy path
        critical: The use case is so important that missing it means the product isn't just incomplete it's straight up unusable. The use case should be realized before anything else.
        high: The use case is important for the product, missing this use case means the product is incomplete. The use case must be realized.
        medium: The use case is needed for the product but not a showstopper. The use case should be realized when practical.
        low: The use case would be useful but everything else should be completed before it is realized.